name: PR Landmine

on:
  pull_request

jobs:
  landmine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: PR Landmine
      uses: tylermurry/github-pr-landmine@v1
      with:
        token: ${{ github.token }}
        test-command: exit ./scripts/bin/test.sh

