name: PR Landmine

on:
  issue_comment:
    types: [created]

jobs:
  landmine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: PR Landmine
      uses: tylermurry/github-pr-landmine@v1
      with:
        token: ${{ github.PAT }}
        test-command: ./scripts/bin/test.sh

